---
title: "Project"
author: "P.K"
date: "2022-11-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}

# Generalized the path

library(readr)
training_set <- read_csv("train.csv")

testing_set <- read_csv("test_new.csv")

```

Scatterplots

```{r}
summary(training_set)
pairs(training_set[,c(4,5,20,21,27)])
pairs(training_set[,c(35,37,38,39)])
pairs(training_set[,c(44:48)])
pairs(training_set[,c(48:53)])
pairs(training_set[,c(55,57,60,62,63)])
pairs(training_set[,c(67:71)])
pairs(training_set[,c(72,76:78)])

pairs(training_set[,c(4,5,27,35,44,63,67)])
```

Boxplots

```{r}
plot(y=training_set$SalePrice, x=as.factor(training_set$MSSubClass))
plot(y=training_set$SalePrice, x=as.factor(training_set$MSZoning))
plot(y=training_set$SalePrice, x=as.factor(training_set$LotShape))
plot(y=training_set$SalePrice, x=as.factor(training_set$Utilities))
plot(y=training_set$SalePrice, x=as.factor(training_set$LandSlope))
plot(y=training_set$SalePrice, x=as.factor(training_set$Neighborhood))
plot(y=training_set$SalePrice, x=as.factor(training_set$Condition1))
plot(y=training_set$SalePrice, x=as.factor(training_set$BldgType))
plot(y=training_set$SalePrice, x=as.factor(training_set$HouseStyle))
plot(y=training_set$SalePrice, x=as.factor(training_set$OverallQual))
plot(y=training_set$SalePrice, x=as.factor(training_set$OverallCond))
plot(y=training_set$SalePrice, x=as.factor(training_set$RoofStyle))
plot(y=training_set$SalePrice, x=as.factor(training_set$ExterQual))
plot(y=training_set$SalePrice, x=as.factor(training_set$Foundation))
plot(y=training_set$SalePrice, x=as.factor(training_set$BsmtCond))
plot(y=training_set$SalePrice, x=as.factor(training_set$Heating))
plot(y=training_set$SalePrice, x=as.factor(training_set$CentralAir))
plot(y=training_set$SalePrice, x=as.factor(training_set$KitchenQual))
plot(y=training_set$SalePrice, x=as.factor(training_set$GarageQual))
plot(y=training_set$SalePrice, x=as.factor(training_set$SaleType))
plot(y=training_set$SalePrice, x=as.factor(training_set$SaleCondition))
```


```{r}

# Ethan's Work

library(MASS)
library(dplyr)
library(tidyr)
library(tibble)
library(reshape2)
library(ggplot2)


# Data is skewed
fit <- fitdistr(training_set$SalePrice, "normal")
para <- fit$estimate
x <- rnorm(1000, para[1],para[2])
hist(training_set$SalePrice, prob = TRUE, breaks = 50, xlab = "Sale Price ($)", ylab = "Density")
curve(dnorm(x,para[1],para[2]), col = 2, add = TRUE)


# Need to reduce dimensions. Likely good to get rid of redundant and correlated 
# variables.

# get numerical variables and make NAs 0
num_train <- Filter(is.numeric, training_set)
num_train[is.na(num_train)] <- 0

num_test <- Filter(is.numeric, testing_set)
num_test[is.na(num_test)] <- 0

cor_mat <- round(cor(num_train),2)

# Correlations limited to combinations >= .60
# remove diagonal and redundant values

cor_mat[!lower.tri(cor_mat)] <- NA 

cor_mat <- data.frame(cor_mat) %>%
              rownames_to_column() %>%
              gather(key="variable", value="correlation", -rowname) %>%
              filter(abs(correlation) >= 0.6)

# Heat map for correlations
p_cors <- round(cor(num_train),2)
threshold <- 0.6
p_cors2 <- p_cors
diag(p_cors2) <- 0
ok <- apply(abs(p_cors2) >= threshold, 1, any)
p_cors <- p_cors[ok, ok]

# Make the correlation matrix into a dataframe
melted_corr_mat <- melt(p_cors)

# plotting the correlation heatmap
ggplot(data = melted_corr_mat, aes(x=Var1, y=Var2,
                                   fill=value)) +
geom_tile() +
geom_text(aes(Var1, Var2, label = value),
          color = "black", size = 3) +
   theme(axis.text.x=element_text(angle=90,hjust=1,vjust=0.5)) +
  scale_fill_gradient(low = "#ffffff", high = "#ff0000", guide = "colorbar")


# linear models
lm.fit_cor <- lm(SalePrice ~ OverallQual + TotalBsmtSF + GrLivArea + GarageCars, data = num_train)
summary(lm.fit_cor)
pred.lm_cor <- predict(lm.fit_cor, newdata = num_test, type = "response")
mean(sum((num_test$SalePrice - pred.lm_cor)^2))


# Regularization + Principle Components.
```
